include: package:lints/recommended.yaml

linter:
  rules:
    # 追加のルール設定
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false # コマンドラインツールなのでprintを許可
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
